# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)
import torch

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
print(torch.__version__)

# Create random tensor
a = torch.rand((7,7))
a

2.6.0+cu124


tensor([[0.8492, 0.0060, 0.8318, 0.4602, 0.5151, 0.7306, 0.9397],
        [0.5706, 0.4622, 0.3444, 0.7468, 0.3523, 0.8636, 0.2078],
        [0.9556, 0.4133, 0.6095, 0.8543, 0.4495, 0.1115, 0.5831],
        [0.2233, 0.0401, 0.7086, 0.6672, 0.7447, 0.8304, 0.6227],
        [0.1281, 0.1551, 0.7900, 0.5653, 0.5396, 0.2791, 0.8122],
        [0.3948, 0.8189, 0.7276, 0.7277, 0.7673, 0.5468, 0.6954],
        [0.9178, 0.4714, 0.1694, 0.3229, 0.6217, 0.7803, 0.4233]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
b = torch.rand((1,7))
# Perform matrix multiplication
b @ a, a @ b.T

(tensor([[2.0035, 1.1339, 1.6192, 1.7266, 1.8567, 2.2320, 1.8108]]),
 tensor([[2.0635],
         [1.5204],
         [1.8400],
         [1.6156],
         [1.4922],
         [2.0832],
         [1.7636]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(1337)

# Create two random tensors
a = torch.rand((5,5))
b = torch.rand((5,5))

# Matrix multiply tensors
a @ b

tensor([[0.8113, 0.9074, 0.7357, 1.0785, 0.9391],
        [0.6914, 0.7856, 0.7768, 0.9962, 0.8146],
        [1.1623, 1.7609, 1.5358, 1.9601, 2.1541],
        [1.0717, 1.2851, 1.1180, 1.4969, 1.3752],
        [1.8861, 1.9343, 1.5271, 1.8041, 1.8921]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1337)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
dev = torch.device("cuda")
# Set random seed
shape=(2,3)
a,b = torch.rand(shape,device=dev),torch.rand(shape,device=dev)
# Check for access to GPU

# Create two random tensors on GPU
a,b

(tensor([[0.8543, 0.6048, 0.8843],
         [0.4151, 0.6221, 0.3111]], device='cuda:0'),
 tensor([[0.8201, 0.1763, 0.2958],
         [0.2863, 0.4492, 0.6812]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
res = a @ b.T
res

tensor([[1.0688, 1.1187],
        [0.5422, 0.6103]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max

# Find min

torch.min(res),torch.max(res)

(tensor(0.5422, device='cuda:0'), tensor(1.1187, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max


# Find arg min
torch.argmin(res),torch.argmax(res)

(tensor(2, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t = torch.rand((1,1,1,10))

# Remove single dimensions


# Print out tensors and their shapes
t[...,:]

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])